name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.1]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: CI=true yarn test --passWithNoTests
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://trusted-locals.github.io/#/feed/news,https://trusted-locals.github.io/#/submit,https://trusted-locals.github.io/#/account,https://trusted-locals.github.io/#/account/login,https://trusted-locals.github.io/#/account/register,https://trusted-locals.github.io/#/account/reset-password'
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: '80'
          minBestPracticesScore: '80'
          minPerformanceScore: '80'
          minProgressiveWebAppScore: '80'
          minSeoScore: '80'
